function main()
    print("Enter your name:")
    local name = io.read()
    print("Hello, " .. name .. "!")
    print("Enter your age:")
    local age = io.read()
    print("You are " .. age .. " years old.")
    print("Enter your favorite color:")
    local color = io.read()
    print("Your favorite color is " .. color .. ".")
    print("Enter your favorite food:")
    local food = io.read()
    print("Your favorite food is " .. food .. ".")
    end
